
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Terms of Service | ToThereOn',
    description: 'Terms of Service for ToThereOn AI Pet Memorial Service.',
}

export default function TermsPage() {
    return (
        <>
            <h1>Terms of Service</h1>
            <p className="lead">Last Updated: March 3, 2026</p>

            <p>
                Please read these Terms of Service (&quot;Terms&quot;) carefully before using ToThereOn (&quot;Service,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By creating an account or using the Service, you confirm that you have read, understood, and agree to be bound by these Terms. If you do not agree, do not use the Service.
            </p>

            {/* ─── 1. NATURE OF SERVICE ─── */}
            <h3>1. Nature of the Service — AI Simulation Disclosure</h3>
            <p>
                <strong>ToThereOn is an AI-powered creative and memorial simulation service.</strong> All &quot;Pet Personas,&quot; status updates, and letters generated through the Service are produced by artificial intelligence (including models operated by Anthropic, PBC and other third-party providers) based solely on information you provide.
            </p>
            <p>
                <strong>The Service does not facilitate actual communication with deceased animals, spirits, or any form of afterlife entity.</strong> Content generated by the Service is fictional and commemorative in nature. It is not a factual representation of any past, present, or future state of your pet.
            </p>
            <p>
                <strong>The Service is not a substitute for professional grief counseling, mental health therapy, psychological treatment, or veterinary advice.</strong> If you are experiencing a mental health crisis, severe grief, or thoughts of self-harm, please contact a licensed mental health professional or a crisis support line immediately.
            </p>

            {/* ─── 2. ELIGIBILITY ─── */}
            <h3>2. Eligibility</h3>
            <p>
                You must be at least <strong>18 years of age</strong> to use the Service. By creating an account, you represent and warrant that you are 18 years of age or older. If you are under 18, you may not use the Service under any circumstances.
            </p>
            <p>
                The Service is intended for personal, non-commercial use by individuals who have experienced the loss of a companion animal.
            </p>

            {/* ─── 3. USER ACCOUNTS ─── */}
            <h3>3. User Accounts</h3>
            <p>
                You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to notify us immediately of any unauthorized use of your account.
            </p>
            <p>
                You may not create accounts on behalf of others, use automated tools to create accounts, or maintain more than one active account without our express written permission.
            </p>

            {/* ─── 4. AI-GENERATED CONTENT ─── */}
            <h3>4. AI-Generated Content — Limitations and Risks</h3>
            <p>
                Artificial intelligence systems are probabilistic and imperfect. The Service may occasionally generate content that is:
            </p>
            <ul>
                <li>Inaccurate, inconsistent, or factually incorrect</li>
                <li>Emotionally distressing, unexpected, or unsatisfactory</li>
                <li>Inconsistent with your pet&apos;s actual personality or behavior</li>
            </ul>
            <p>
                <strong>You agree to use AI-generated content at your own risk.</strong> We do not guarantee that generated content will meet your expectations, accurately reflect your pet&apos;s character, or be free from errors. We are not liable for any emotional distress, psychological harm, or dissatisfaction arising from AI-generated content.
            </p>

            {/* ─── 5. USER CONTENT ─── */}
            <h3>5. User Content and License</h3>
            <p>
                You retain all ownership rights to content you upload to the Service, including photographs, letters, and written descriptions (&quot;User Content&quot;).
            </p>
            <p>
                By uploading User Content, you grant ToThereOn a limited, non-exclusive, worldwide, royalty-free license to use, process, store, and transmit your User Content solely for the purpose of providing and improving the Service to you. This license does not extend to selling, licensing, or publicly distributing your User Content to third parties.
            </p>
            <p>
                <strong>We will not use your photographs, letters, or personal pet memories to train public AI models or sell them to third parties for any purpose.</strong> Your User Content is used only to generate and maintain your pet&apos;s persona within the Service.
            </p>
            <p>
                You represent and warrant that: (a) you own or have the right to upload all User Content; (b) your User Content does not violate any third-party intellectual property rights; and (c) your User Content does not contain illegal, harmful, or explicit material.
            </p>

            {/* ─── 6. SUBSCRIPTIONS & PAYMENTS ─── */}
            <h3>6. Subscriptions and Payments</h3>
            <p>
                Payments are processed by <strong>Paddle</strong>, our Merchant of Record. By subscribing, you also agree to Paddle&apos;s Terms of Service and Privacy Policy. We do not store your payment card information.
            </p>
            <p>
                Paid subscriptions automatically renew at the end of each billing period unless canceled before the renewal date. You may cancel your subscription at any time through your account settings or through Paddle&apos;s customer portal.
            </p>
            <p>
                <strong>Refund Policy:</strong> We offer refunds at our discretion for verified technical failures that prevented access to paid features. Refunds are not available solely due to dissatisfaction with AI-generated content. For any refund requests, please contact our support team within 14 days of the relevant charge.
            </p>
            <p>
                We reserve the right to modify subscription pricing. We will provide at least <strong>30 days&apos; advance notice</strong> of any price changes to active subscribers via the email address associated with your account.
            </p>

            {/* ─── 7. DATA RETENTION AND SERVICE CONTINUITY ─── */}
            <h3>7. Data Retention and Service Continuity</h3>
            <p>
                <strong>Active Subscriptions:</strong> While your subscription is active, your pet&apos;s persona, generated letters, and all Service data are preserved and accessible.
            </p>
            <p>
                <strong>After Cancellation:</strong> If you cancel your subscription, your data (including your pet&apos;s persona and generated content) will be retained for a period of <strong>12 months</strong> from the date of cancellation, during which you may reactivate your subscription and resume access. After 12 months of inactivity, we reserve the right to permanently delete your data.
            </p>
            <p>
                <strong>Account Deletion:</strong> If you request deletion of your account, all associated data will be permanently deleted within 30 days. This action is irreversible.
            </p>
            <p>
                <strong>Service Discontinuation:</strong> In the event that we discontinue the Service entirely, we will provide at least <strong>90 days&apos; advance notice</strong> to all active subscribers, offer a pro-rated refund for prepaid periods, and provide a data export tool so you may download all generated content associated with your account before closure.
            </p>
            <p>
                Marketing language such as &quot;your pet will never disappear&quot; refers to our commitment to preserving your data for the duration of an active or recently lapsed subscription, as described above, and does not constitute a guarantee of perpetual service operation.
            </p>

            {/* ─── 8. PROHIBITED CONDUCT ─── */}
            <h3>8. Prohibited Conduct</h3>
            <p>You agree not to:</p>
            <ul>
                <li>Upload content that is illegal, obscene, defamatory, or that infringes on third-party rights</li>
                <li>Use the Service to harass, impersonate, or harm others</li>
                <li>Attempt to reverse-engineer, scrape, or otherwise extract data or models from the Service</li>
                <li>Use automated systems to access the Service without our express permission</li>
                <li>Use the Service for any commercial purpose without our written consent</li>
                <li>Circumvent or attempt to circumvent any subscription or access restrictions</li>
            </ul>

            {/* ─── 9. INTELLECTUAL PROPERTY ─── */}
            <h3>9. Intellectual Property</h3>
            <p>
                The Service, including its software, design, text, graphics, and AI systems, is owned by ToThereOn and protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works from any part of the Service without our express written permission.
            </p>
            <p>
                AI-generated letters and content produced by the Service on your behalf are provided to you for personal use only. You may download and retain personal copies of generated content for non-commercial memorial purposes.
            </p>

            {/* ─── 10. DISCLAIMER OF WARRANTIES ─── */}
            <h3>10. Disclaimer of Warranties</h3>
            <p>
                <strong>The Service is provided &quot;as is&quot; and &quot;as available,&quot; without warranty of any kind, express or implied.</strong> We do not warrant that the Service will be uninterrupted, error-free, or free from harmful components. We do not warrant the accuracy, completeness, or emotional suitability of AI-generated content.
            </p>
            <p>
                To the maximum extent permitted by applicable law, we disclaim all warranties, including implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
            </p>

            {/* ─── 11. LIMITATION OF LIABILITY ─── */}
            <h3>11. Limitation of Liability</h3>
            <p>
                To the maximum extent permitted by applicable law, ToThereOn and its officers, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages — including but not limited to emotional distress, loss of data, or loss of profits — arising from your use of or inability to use the Service.
            </p>
            <p>
                Our total aggregate liability to you for any claims arising under these Terms shall not exceed the greater of: (a) the total amount you paid to us in the 12 months preceding the claim, or (b) USD $100.
            </p>

            {/* ─── 12. INDEMNIFICATION ─── */}
            <h3>12. Indemnification</h3>
            <p>
                You agree to defend, indemnify, and hold harmless ToThereOn from any claims, damages, or expenses (including reasonable legal fees) arising from: (a) your use of the Service; (b) your User Content; or (c) your violation of these Terms.
            </p>

            {/* ─── 13. CHANGES TO TERMS ─── */}
            <h3>13. Changes to These Terms</h3>
            <p>
                We may update these Terms from time to time. If we make material changes, we will notify you via email and/or a prominent notice within the Service at least <strong>14 days</strong> before the changes take effect. Your continued use of the Service after the effective date constitutes acceptance of the revised Terms.
            </p>

            {/* ─── 14. GOVERNING LAW & DISPUTE RESOLUTION ─── */}
            <h3>14. Governing Law and Dispute Resolution</h3>
            <p>
                These Terms are governed by the laws of the State of Delaware, United States, without regard to its conflict of law principles. Subject to the arbitration agreement below, you and ToThereOn consent to the exclusive jurisdiction of the state and federal courts located in Delaware for any disputes not subject to arbitration.
            </p>

            <h4>14.1 Informal Resolution</h4>
            <p>
                Before initiating any formal dispute, you agree to contact us at <strong>support@tothereon.com</strong> and give us at least <strong>30 days</strong> to attempt to resolve the dispute informally. This requirement does not apply to claims for injunctive relief or intellectual property disputes.
            </p>

            <h4>14.2 Binding Arbitration</h4>
            <p>
                <strong>PLEASE READ THIS SECTION CAREFULLY — IT AFFECTS YOUR LEGAL RIGHTS.</strong>
            </p>
            <p>
                Except as set forth in Section 14.3 below, any Dispute (as defined below) that cannot be resolved informally shall be resolved exclusively by <strong>binding individual arbitration</strong> administered by the American Arbitration Association (&quot;AAA&quot;) under its Consumer Arbitration Rules (available at www.adr.org), rather than in court. The arbitration shall be conducted in English. The arbitrator&apos;s award shall be final and binding, and judgment upon the award may be entered in any court of competent jurisdiction.
            </p>
            <p>
                &quot;Dispute&quot; means any claim, controversy, or dispute between you and ToThereOn arising out of or relating to these Terms, the Service, or any aspect of our relationship, whether based in contract, tort, statute, fraud, misrepresentation, or any other legal theory.
            </p>
            <p>
                <strong>Costs:</strong> If your claim does not exceed $10,000, ToThereOn will pay all AAA filing, administration, and arbitrator fees unless the arbitrator finds your claim frivolous. For claims exceeding $10,000, the AAA Consumer Arbitration Rules govern fee allocation.
            </p>

            <h4>14.3 Exceptions to Arbitration</h4>
            <p>The following disputes are <strong>not</strong> subject to binding arbitration:</p>
            <ul>
                <li>Claims that qualify for <strong>small claims court</strong> in your jurisdiction</li>
                <li>Claims seeking emergency injunctive or equitable relief to prevent infringement of intellectual property rights</li>
                <li>Claims that applicable law expressly prohibits from being arbitrated</li>
            </ul>

            <h4>14.4 Class Action Waiver</h4>
            <p>
                <strong>YOU AND TOTHEREON AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, CONSOLIDATED, OR REPRESENTATIVE PROCEEDING.</strong> The arbitrator may not consolidate more than one person&apos;s claims and may not preside over any form of class or representative proceeding.
            </p>
            <p>
                If a court finds the class action waiver unenforceable as to any claim, that claim shall be severed from arbitration and litigated in court, while all other claims remain subject to arbitration.
            </p>

            <h4>14.5 Arbitration Opt-Out</h4>
            <p>
                You may opt out of the binding arbitration agreement by sending written notice to <strong>support@tothereon.com</strong> within <strong>30 days</strong> of the date you first create your account. Your notice must include your name, email address, and a clear statement that you wish to opt out of arbitration. If you opt out, disputes will be resolved in the state or federal courts located in Delaware, and both parties consent to personal jurisdiction in those courts.
            </p>
            <p>
                Opting out of arbitration does not affect any other part of these Terms and will not affect your ability to use the Service.
            </p>

            {/* ─── 15. DMCA ─── */}
            <h3>15. Copyright — DMCA Policy</h3>
            <p>
                ToThereOn respects intellectual property rights and expects users to do the same. If you believe that your copyrighted work has been copied or used on the Service in a way that constitutes copyright infringement, please submit a written notice to our designated copyright agent that includes all of the following:
            </p>
            <ul>
                <li>A physical or electronic signature of the copyright owner or an authorized agent</li>
                <li>Identification of the copyrighted work claimed to have been infringed</li>
                <li>Identification of the material on the Service that is claimed to be infringing, with sufficient detail to locate it (e.g., a URL)</li>
                <li>Your contact information (name, address, telephone number, and email address)</li>
                <li>A statement that you have a good-faith belief that the use of the material is not authorized by the copyright owner, its agent, or the law</li>
                <li>A statement, under penalty of perjury, that the information in the notice is accurate and that you are authorized to act on behalf of the copyright owner</li>
            </ul>
            <p>
                <strong>DMCA Agent:</strong> support@tothereon.com (Subject line: &quot;DMCA Takedown Notice&quot;)
            </p>
            <p>
                Upon receiving a valid DMCA notice, we will promptly remove or disable access to the allegedly infringing material and notify the user who posted it. That user may submit a counter-notice if they believe the removal was in error. Repeated infringers will have their accounts terminated.
            </p>
            <p>
                <strong>Warning:</strong> Submitting a false or misleading DMCA notice may expose you to legal liability, including damages and attorneys&apos; fees, under 17 U.S.C. § 512(f).
            </p>

            {/* ─── 16. CONTACT ─── */}
            <h3>16. Contact</h3>
            <p>
                For questions, concerns, or requests related to these Terms, please contact us at: <strong>support@tothereon.com</strong>
            </p>
        </>
    )
}
