'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import Link from 'next/link'

interface ConsentModalProps {
    isOpen: boolean
    onAccept: () => void
}

const CONSENT_ITEMS = [
    {
        id: 'ai_simulation',
        label: 'I understand that ToThereOn is an AI simulation service.',
        detail: 'All letters, status updates, and content are generated by artificial intelligence based on the information I provide. This service does not facilitate real communication with deceased animals or any form of afterlife.',
    },
    {
        id: 'not_therapy',
        label: 'I understand this service is not a substitute for professional grief support.',
        detail: 'ToThereOn is a creative memorial service. It is not a mental health treatment, grief therapy, or counseling service. I will seek professional support if I am experiencing a mental health crisis.',
    },
    {
        id: 'data_processing',
        label: 'I consent to my photos and letters being processed by AI systems to generate content for me.',
        detail: 'The photos and letters I upload will be sent to third-party AI providers (Anthropic Claude) solely to create and maintain my pet\'s persona. My data will never be sold or used to train public AI models.',
    },
    {
        id: 'age_confirm',
        label: 'I confirm that I am 18 years of age or older.',
        detail: 'This service is intended for adults. Use by individuals under 18 is not permitted.',
    },
]

export function ConsentModal({ isOpen, onAccept }: ConsentModalProps) {
    const [checked, setChecked] = useState<Record<string, boolean>>({})
    const [expanded, setExpanded] = useState<string | null>(null)

    const allChecked = CONSENT_ITEMS.every(item => checked[item.id])

    const toggle = (id: string) => {
        setChecked(prev => ({ ...prev, [id]: !prev[id] }))
    }

    return (
        <AnimatePresence>
            {isOpen && (
                <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/50 backdrop-blur-sm p-4"
                >
                    <motion.div
                        initial={{ opacity: 0, scale: 0.96, y: 16 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.96, y: 16 }}
                        transition={{ duration: 0.25 }}
                        className="bg-white rounded-3xl shadow-2xl w-full max-w-lg max-h-[90vh] flex flex-col"
                    >
                        {/* Header */}
                        <div className="px-8 pt-8 pb-6 border-b border-slate-100">
                            <h2 className="text-xl font-bold text-slate-900 mb-1">
                                Before you begin
                            </h2>
                            <p className="text-sm text-slate-500 leading-relaxed">
                                Please read and confirm each item below. This takes less than a minute and ensures we&apos;re on the same page.
                            </p>
                        </div>

                        {/* Consent Items */}
                        <div className="px-8 py-6 space-y-4 overflow-y-auto flex-1">
                            {CONSENT_ITEMS.map(item => (
                                <div
                                    key={item.id}
                                    className={`rounded-2xl border transition-all duration-200 ${
                                        checked[item.id]
                                            ? 'border-sky-200 bg-sky-50/50'
                                            : 'border-slate-200 bg-white'
                                    }`}
                                >
                                    {/* Checkbox Row */}
                                    <label className="flex items-start gap-4 px-5 py-4 cursor-pointer">
                                        <div className="mt-0.5 flex-shrink-0">
                                            <div
                                                onClick={() => toggle(item.id)}
                                                className={`w-5 h-5 rounded-md border-2 flex items-center justify-center transition-all duration-150 ${
                                                    checked[item.id]
                                                        ? 'bg-sky-500 border-sky-500'
                                                        : 'border-slate-300 bg-white'
                                                }`}
                                            >
                                                {checked[item.id] && (
                                                    <svg className="w-3 h-3 text-white" fill="none" viewBox="0 0 12 12">
                                                        <path d="M2 6l3 3 5-5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                                                    </svg>
                                                )}
                                            </div>
                                        </div>
                                        <span
                                            className={`text-sm font-medium leading-snug transition-colors ${
                                                checked[item.id] ? 'text-slate-800' : 'text-slate-700'
                                            }`}
                                            onClick={() => toggle(item.id)}
                                        >
                                            {item.label}
                                        </span>
                                        {/* Expand detail toggle */}
                                        <button
                                            type="button"
                                            onClick={e => {
                                                e.stopPropagation()
                                                setExpanded(expanded === item.id ? null : item.id)
                                            }}
                                            className="ml-auto flex-shrink-0 text-slate-400 hover:text-slate-600 transition-colors"
                                            aria-label="Show detail"
                                        >
                                            <svg
                                                className={`w-4 h-4 transition-transform duration-200 ${expanded === item.id ? 'rotate-180' : ''}`}
                                                fill="none" viewBox="0 0 24 24" stroke="currentColor"
                                            >
                                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                                            </svg>
                                        </button>
                                    </label>

                                    {/* Expandable Detail */}
                                    <AnimatePresence>
                                        {expanded === item.id && (
                                            <motion.div
                                                initial={{ height: 0, opacity: 0 }}
                                                animate={{ height: 'auto', opacity: 1 }}
                                                exit={{ height: 0, opacity: 0 }}
                                                transition={{ duration: 0.2 }}
                                                className="overflow-hidden"
                                            >
                                                <p className="px-5 pb-4 text-xs text-slate-500 leading-relaxed border-t border-slate-100 pt-3">
                                                    {item.detail}
                                                </p>
                                            </motion.div>
                                        )}
                                    </AnimatePresence>
                                </div>
                            ))}
                        </div>

                        {/* Footer */}
                        <div className="px-8 pb-8 pt-4 border-t border-slate-100">
                            <button
                                onClick={onAccept}
                                disabled={!allChecked}
                                className={`w-full py-3.5 rounded-2xl text-sm font-semibold transition-all duration-200 ${
                                    allChecked
                                        ? 'bg-slate-900 text-white hover:bg-slate-800 shadow-sm'
                                        : 'bg-slate-100 text-slate-400 cursor-not-allowed'
                                }`}
                            >
                                {allChecked ? 'I understand — Continue' : `${Object.values(checked).filter(Boolean).length} of ${CONSENT_ITEMS.length} confirmed`}
                            </button>
                            <p className="mt-4 text-center text-xs text-slate-400 leading-relaxed">
                                By continuing, you also agree to our{' '}
                                <Link href="/terms" target="_blank" className="underline hover:text-slate-600">Terms of Service</Link>
                                {' '}and{' '}
                                <Link href="/privacy" target="_blank" className="underline hover:text-slate-600">Privacy Policy</Link>.
                            </p>
                        </div>
                    </motion.div>
                </motion.div>
            )}
        </AnimatePresence>
    )
}
