/**
 * Micro-Event Templates — ToThereOn v2
 * ~92 templates across 6 categories.
 *
 * Rules enforced:
 * - Max 2 sentences per template
 * - Narrator perspective (not the pet's voice), describing what the pet does
 * - Sensory/action detail only — no stated emotion, no interpretation
 * - {petName}, {zoneName}, {npcName}, {secretHabit}, {preciousMemory} interpolation
 * - Korean: {eun}/{i}/{eul} placeholders resolved at render time by koreanParticle()
 * - ZERO forbidden words: happy, sad, joyful, grateful, blessed, heaven, rainbow bridge,
 *   death, die, passed away, loss, grief, mourning, "as if remembering", "seemed to feel", etc.
 */

import type { MicroEventTemplate } from './micro-event-types';

// ─────────────────────────────────────────────────────────────────────────────
// CATEGORY 1: ATMOSPHERE (20 templates — 5 morning, 5 afternoon, 5 evening, 5 night)
// ─────────────────────────────────────────────────────────────────────────────

const ATMOSPHERE_TEMPLATES: MicroEventTemplate[] = [
    // ── Morning (5) ──────────────────────────────────────────────────────────
    {
        id: 'atm_morning_meadow_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning'],
        zones: ['crystal_meadow'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The first light crept across Crystal Meadow. {petName} lifted a nose to the warm air.',
            ko: '첫 햇살이 수정 초원 위로 번졌다. {petName}{eun} 따뜻한 공기에 코를 들었다.',
            ja: '最初の光がクリスタルメドウに差し込んだ。{petName}は暖かい空気に鼻を持ち上げた。',
        },
        mood: 'peaceful',
        tags: ['gentle', 'morning', 'sensory'],
    },
    {
        id: 'atm_morning_forest_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning'],
        zones: ['eternity_forest'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'Dew gathered on every fern in Eternity Forest, and the blue moss glowed faintly in the low light. {petName} picked a path between the wet roots.',
            ko: '영원의 숲 고사리마다 이슬이 맺혔고 파란 이끼가 낮은 빛 속에서 희미하게 빛났다. {petName}{eun} 젖은 나무뿌리 사이로 길을 골랐다.',
            ja: '永遠の森のシダにはすべて露が結び、青い苔が低い光の中でかすかに輝いていた。{petName}は濡れた根の間に道を選んだ。',
        },
        mood: 'quiet',
        tags: ['morning', 'forest', 'sensory'],
    },
    {
        id: 'atm_morning_lake_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning'],
        zones: ['crystal_lake'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'Crystal Lake lay perfectly flat in the morning, the far shore still in shadow. {petName} sat at the water\'s edge until the shadow moved.',
            ko: '수정 호수가 아침에 완전히 평평하게 누워 있었고 건너편 기슭은 아직 그늘 속이었다. {petName}{eun} 그늘이 움직일 때까지 물가에 앉아 있었다.',
            ja: 'クリスタルレイクは朝、完全に平らに横たわり、対岸はまだ影の中にあった。{petName}は影が動くまで水辺に座っていた。',
        },
        mood: 'still',
        tags: ['morning', 'lake', 'water'],
    },
    {
        id: 'atm_morning_hill_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning'],
        zones: ['sunset_hill'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'Wind moved through the tall grass on Sunset Hill before the light arrived, bending it all one direction. {petName} climbed toward the crest.',
            ko: '빛이 오기 전에 바람이 석양 언덕 키 큰 풀밭을 지나가며 모두 한 방향으로 구부렸다. {petName}{eun} 능선을 향해 올랐다.',
            ja: '光が届く前に風が夕日の丘の背の高い草の中を通り抜け、すべてを一方向に曲げた。{petName}は稜線へと登っていった。',
        },
        mood: 'anticipating',
        tags: ['morning', 'hill', 'wind'],
    },
    {
        id: 'atm_morning_plaza_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The Waterway ran clear and quick through Central Plaza at this hour, catching the first gold off the sky. {petName} stood at the bank and watched the current for a long moment.',
            ko: '수로는 이 시간에 중앙 광장을 가로질러 맑고 빠르게 흘렀고 하늘에서 첫 번째 황금빛을 받았다. {petName}{eun} 둑에 서서 한참 동안 물살을 바라봤다.',
            ja: 'この時間、水の道は中央広場を澄んで素早く流れ、空から最初の金色を受けていた。{petName}は土手に立ち、長い間流れを眺めていた。',
        },
        mood: 'attentive',
        tags: ['morning', 'waterway', 'light'],
    },

    // ── Afternoon (5) ────────────────────────────────────────────────────────
    {
        id: 'atm_afternoon_meadow_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['afternoon'],
        zones: ['crystal_meadow'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The crystal flowers in the meadow caught the high sun and scattered it in moving patches across the grass. {petName} moved through the light as if tracing a path.',
            ko: '초원의 수정 꽃들이 높은 햇볕을 받아 풀밭 위에 움직이는 빛 조각들을 흩뿌렸다. {petName}{eun} 길을 따라가듯 그 빛 속을 지나갔다.',
            ja: '草原の水晶の花が高い太陽を受け、草の上に動く光の斑点を散らした。{petName}は道をたどるように光の中を進んだ。',
        },
        mood: 'alert',
        tags: ['afternoon', 'meadow', 'light'],
    },
    {
        id: 'atm_afternoon_forest_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['afternoon'],
        zones: ['eternity_forest'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'Afternoon in Eternity Forest brought sharp shadows between the silver-barked trees and a stillness that pressed against sound. {petName} rested in one of those shadows, flanks rising and falling.',
            ko: '오후의 영원의 숲에는 은빛 나무껍질 사이로 날카로운 그림자가 지고 소리를 압박하는 고요함이 찾아왔다. {petName}{eun} 그 그림자 속에서 옆구리를 오르내리며 쉬었다.',
            ja: '午後の永遠の森は銀の木肌の間に鋭い影をもたらし、音を圧迫するような静けさがあった。{petName}はその影の一つで横腹を上下させながら休んでいた。',
        },
        mood: 'resting',
        tags: ['afternoon', 'forest', 'shade'],
    },
    {
        id: 'atm_afternoon_lake_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['afternoon'],
        zones: ['crystal_lake'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The lake warmed through by midday, smooth stones visible all the way to the bottom of the cove. {petName} stepped in up to the ankles, then stopped.',
            ko: '호수는 한낮이 되자 완전히 따뜻해졌고 작은 만 바닥까지 매끈한 돌들이 보였다. {petName}{eun} 발목까지 들어갔다가 멈췄다.',
            ja: '湖は昼頃には温まり、入り江の底まで滑らかな石が見えた。{petName}は足首まで入り、そして止まった。',
        },
        mood: 'curious',
        tags: ['afternoon', 'lake', 'water'],
    },
    {
        id: 'atm_afternoon_hill_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['afternoon'],
        zones: ['sunset_hill'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'Gold pollen drifted off the hillside grasses in small clouds, catching the light before settling on every surface it touched. {petName} sneezed once, then kept moving uphill.',
            ko: '언덕 풀밭에서 황금 꽃가루가 작은 구름처럼 날리다 빛을 받고는 닿는 모든 곳에 내려앉았다. {petName}{eun} 한 번 재채기를 하고는 계속 언덕을 올랐다.',
            ja: '丘の草から金色の花粉が小さな雲のように漂い、触れるすべての表面に落ち着く前に光を受けた。{petName}は一度くしゃみをして、また丘を登り続けた。',
        },
        mood: 'active',
        tags: ['afternoon', 'hill', 'pollen'],
    },
    {
        id: 'atm_afternoon_plaza_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['afternoon'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The plaza was at its most active in the afternoon, voices and movement filling the space near the Waterway. {petName} circled the outer edge twice before finding a spot.',
            ko: '광장은 오후에 가장 활기찼고 수로 근처 공간이 목소리와 움직임으로 가득 찼다. {petName}{eun} 자리를 찾기 전에 외곽을 두 번 돌았다.',
            ja: '広場は午後が最も賑わい、水の道近くの空間が声と動きで満ちた。{petName}は場所を見つける前に外縁を二度回った。',
        },
        mood: 'cautious',
        tags: ['afternoon', 'plaza', 'social'],
    },

    // ── Evening (5) ──────────────────────────────────────────────────────────
    {
        id: 'atm_evening_meadow_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['evening'],
        zones: ['crystal_meadow'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The meadow turned copper as the light came down, the crystal flowers holding color long after everything else had dimmed. {petName} lay among them with eyes open.',
            ko: '초원은 빛이 내려오면서 구릿빛으로 변했고 수정 꽃들은 다른 모든 것이 어두워진 뒤에도 오래 색을 간직했다. {petName}{eun} 눈을 뜨고 그 꽃들 사이에 누워 있었다.',
            ja: '光が降りるにつれて草原は銅色に変わり、水晶の花はほかのすべてが暗くなった後も長く色を保った。{petName}は目を開けてその中に横たわっていた。',
        },
        mood: 'still',
        tags: ['evening', 'meadow', 'light'],
    },
    {
        id: 'atm_evening_hill_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['evening'],
        zones: ['sunset_hill'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'Both moons were visible over Sunset Hill at this hour — the near one bright, the far one a faint smudge of silver. {petName} sat at the crest and did not move for a long time.',
            ko: '이 시간에 두 달이 석양 언덕 위로 보였다 — 가까운 달은 밝고 먼 달은 희미한 은빛 얼룩이었다. {petName}{eun} 능선에 앉아 오랫동안 움직이지 않았다.',
            ja: 'この時間、夕日の丘の上に両方の月が見えた——近い月は明るく、遠い月はかすかな銀色のしみだった。{petName}は稜線に座り、長い間動かなかった。',
        },
        mood: 'contemplative',
        tags: ['evening', 'hill', 'moons'],
    },
    {
        id: 'atm_evening_lake_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['evening'],
        zones: ['crystal_lake'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The lake\'s surface turned violet in the last light, the reflection pool and the real water almost indistinguishable. {petName} dipped one paw in, then pulled it back.',
            ko: '호수 표면이 마지막 빛 속에서 보랏빛으로 변했고 반영 못과 실제 물이 거의 구별되지 않았다. {petName}{eun} 앞발 하나를 담갔다가 뒤로 뺐다.',
            ja: '湖面は最後の光の中で紫に変わり、反映の池と本物の水がほとんど区別できなかった。{petName}は前足を一つ浸し、それから引き戻した。',
        },
        mood: 'reflective',
        tags: ['evening', 'lake', 'water'],
    },
    {
        id: 'atm_evening_forest_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['evening'],
        zones: ['eternity_forest'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'As the forest darkened, the blue moss began its glow in earnest, tracing the roots and lower trunks in cold light. {petName} followed one lit root until it disappeared into earth.',
            ko: '숲이 어두워지면서 파란 이끼가 본격적으로 빛나기 시작해 차가운 빛으로 뿌리와 아래쪽 나무 줄기를 따라갔다. {petName}{eun} 빛나는 뿌리 하나를 땅속으로 사라질 때까지 따라갔다.',
            ja: '森が暗くなるにつれて、青い苔が本格的に光り始め、冷たい光で根と木の下部をたどった。{petName}は光る根の一本が土に消えるまで追いかけた。',
        },
        mood: 'curious',
        tags: ['evening', 'forest', 'moss'],
    },
    {
        id: 'atm_evening_plaza_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['evening'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The Waterway caught the last violet light and sent it rippling under the stone arch of the Arriving Gate. {petName} watched it from the near bank without approaching.',
            ko: '수로가 마지막 보랏빛을 받아 도착의 문 돌아치 아래로 물결치며 보냈다. {petName}{eun} 가까이 가지 않고 가까운 둑에서 지켜봤다.',
            ja: '水の道が最後の紫の光を受け、到着の門の石のアーチの下に波紋を送った。{petName}は近づかずに近い土手からそれを眺めた。',
        },
        mood: 'watchful',
        tags: ['evening', 'plaza', 'waterway'],
    },

    // ── Night (5) ────────────────────────────────────────────────────────────
    {
        id: 'atm_night_meadow_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['night'],
        zones: ['crystal_meadow'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The meadow was silver and very quiet after dark, the crystal flowers catching moonlight the way they caught sunlight. {petName} moved through it without disturbing the stillness.',
            ko: '초원은 어두워진 후 은빛으로 아주 고요해졌고 수정 꽃들이 햇빛을 받듯 달빛을 받았다. {petName}{eun} 고요함을 흩뜨리지 않고 그 속을 지나갔다.',
            ja: '草原は暗くなった後、銀色でとても静かになり、水晶の花は日光を受けるように月光を受けた。{petName}はその静けさを乱さずに進んだ。',
        },
        mood: 'silvered',
        tags: ['night', 'meadow', 'moonlight'],
    },
    {
        id: 'atm_night_forest_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['night'],
        zones: ['eternity_forest'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'At night the forest paths were defined entirely by the blue moss — everything outside its light was formless. {petName} moved from glow to glow like stepping-stones.',
            ko: '밤에는 숲길이 온전히 파란 이끼로만 구분됐다 — 그 빛 바깥의 모든 것은 형태가 없었다. {petName}{eun} 징검다리처럼 빛에서 빛으로 이동했다.',
            ja: '夜、森の道は完全に青い苔だけで区切られていた——その光の外にあるものはすべて形がなかった。{petName}は飛び石のように光から光へと移動した。',
        },
        mood: 'focused',
        tags: ['night', 'forest', 'moss'],
    },
    {
        id: 'atm_night_lake_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['night'],
        zones: ['crystal_lake'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'Crystal Lake held both moons in its surface at night, the reflections stretching to the shore. {petName} lay on the pebble bank and looked up at the real ones instead.',
            ko: '밤에 수정 호수는 표면에 두 달을 담고 반사가 기슭까지 뻗었다. {petName}{eun} 조약돌 둑에 누워 대신 실제 달들을 올려다봤다.',
            ja: '夜、クリスタルレイクは水面に両方の月を映し、反射が岸まで伸びていた。{petName}は小石の土手に横になって代わりに本物の月を見上げた。',
        },
        mood: 'contemplative',
        tags: ['night', 'lake', 'moons'],
    },
    {
        id: 'atm_night_hill_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['night'],
        zones: ['sunset_hill'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The wind on Sunset Hill at night carried a scent that had no source — not the grass, not the stone, something further away. {petName} lifted its nose and held the direction.',
            ko: '밤의 석양 언덕에서 바람이 출처 없는 냄새를 실어왔다 — 풀도 돌도 아닌 더 멀리서 온 무언가. {petName}{eun} 코를 들고 그 방향을 잡았다.',
            ja: '夜の夕日の丘の風は、出所のない香りを運んでいた——草でも石でもなく、もっと遠くからのもの。{petName}は鼻を上げてその方向を保った。',
        },
        mood: 'attentive',
        tags: ['night', 'hill', 'scent'],
    },
    {
        id: 'atm_night_plaza_01',
        category: 'atmosphere',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['night'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The Waterway ran quieter at night, a soft sound against the stone banks. {petName} found a spot near the arch and curled close to the sound of it.',
            ko: '수로는 밤에 더 조용히 흘렀고 돌 둑에 부드러운 소리를 냈다. {petName}{eun} 아치 근처에 자리를 찾아 그 소리 가까이 웅크렸다.',
            ja: '水の道は夜は静かに流れ、石の土手に柔らかな音をたてた。{petName}はアーチの近くに場所を見つけ、その音の近くに丸まった。',
        },
        mood: 'settled',
        tags: ['night', 'plaza', 'waterway'],
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// CATEGORY 2: PET_ACTION (25 templates — personality-specific behavioral vignettes)
// ─────────────────────────────────────────────────────────────────────────────

const PET_ACTION_TEMPLATES: MicroEventTemplate[] = [
    // ── Shy ──────────────────────────────────────────────────────────────────
    {
        id: 'act_shy_approach_01',
        category: 'pet_action',
        species: ['any'],
        personalityBuckets: ['shy'],
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: '{petName} stopped at the edge of the open ground and waited there for a full stretch before continuing. The space was empty — but that did not seem to matter.',
            ko: '{petName}{eun} 열린 공간의 가장자리에서 멈춰 한참을 기다리다 계속 나아갔다. 공간은 비어 있었지만 그게 중요한 것 같지 않았다.',
            ja: '{petName}は開けた地面の端で止まり、進む前にたっぷり待った。空間は空っぽだったが、それは関係ないようだった。',
        },
        mood: 'cautious',
        tags: ['shy', 'hesitation', 'boundary'],
    },
    {
        id: 'act_shy_watch_01',
        category: 'pet_action',
        species: ['any'],
        personalityBuckets: ['shy'],
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: '{petName} found a spot above the path where the view ran long in both directions, and settled there. The watching seemed to be the purpose.',
            ko: '{petName}{eun} 길 위 양방향으로 시야가 길게 트인 자리를 찾아 거기에 자리 잡았다. 바라보는 것 자체가 목적인 듯했다.',
            ja: '{petName}は道の上、両方向に視界が長く通る場所を見つけ、そこに落ち着いた。見ていること自体が目的のようだった。',
        },
        mood: 'watchful',
        tags: ['shy', 'observation', 'perch'],
    },
    {
        id: 'act_shy_retreat_01',
        category: 'pet_action',
        species: ['any'],
        personalityBuckets: ['shy'],
        timeOfDay: 'all',
        zones: ['eternity_forest', 'crystal_meadow'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'When three others arrived at the same clearing, {petName} moved quietly to the far side without drawing attention. Same clearing — different edge.',
            ko: '다른 셋이 같은 빈터에 나타났을 때 {petName}{eun} 눈에 띄지 않게 반대편으로 조용히 이동했다. 같은 빈터, 다른 가장자리.',
            ja: '他の三匹が同じ空き地に現れると、{petName}は注目を集めずに静かに反対側に移動した。同じ空き地——違う端。',
        },
        mood: 'careful',
        tags: ['shy', 'social-distance', 'quiet'],
    },
    {
        id: 'act_shy_nap_01',
        category: 'pet_action',
        species: ['any'],
        personalityBuckets: ['shy'],
        timeOfDay: ['afternoon', 'evening'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: '{petName} chose the narrowest gap between two large roots — just wide enough to fit — and slept there for the whole of the afternoon.',
            ko: '{petName}{eun} 두 큰 뿌리 사이에서 딱 들어갈 만한 가장 좁은 틈을 골라 오후 내내 그곳에서 잤다.',
            ja: '{petName}はちょうど入れるだけの二本の大きな根の間の最も狭い隙間を選び、午後中そこで眠った。',
        },
        mood: 'secure',
        tags: ['shy', 'shelter', 'rest'],
    },

    // ── Bold ─────────────────────────────────────────────────────────────────
    {
        id: 'act_bold_explore_01',
        category: 'pet_action',
        species: ['any'],
        personalityBuckets: ['bold'],
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: '{petName} crossed to the far side of {zoneName} that most others only look at from a distance. Came back covered in a new color of soil.',
            ko: '{petName}{eun} 다른 대부분이 멀리서만 바라보는 {zoneName}의 반대편을 가로질렀다. 새로운 색의 흙을 묻히고 돌아왔다.',
            ja: '{petName}は他の多くが遠くから眺めるだけの{zoneName}の反対側を横断した。新しい色の土をつけて戻ってきた。',
        },
        mood: 'adventurous',
        tags: ['bold', 'exploration', 'first-time'],
    },
    {
        id: 'act_bold_claim_01',
        category: 'pet_action',
        species: ['dog'],
        personalityBuckets: ['bold'],
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: '{petName} found the highest flat stone in {zoneName} and stood on it, taking in the full view before stepping down again.',
            ko: '{petName}{eun} {zoneName}에서 가장 높고 평평한 돌을 찾아 올라서서 전체 경치를 바라본 뒤 다시 내려왔다.',
            ja: '{petName}は{zoneName}で最も高く平らな石を見つけ、その上に立ち、全景を眺めてから再び降りた。',
        },
        mood: 'confident',
        tags: ['bold', 'elevated', 'survey'],
    },
    {
        id: 'act_bold_greet_01',
        category: 'pet_action',
        species: ['any'],
        personalityBuckets: ['bold'],
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'A newcomer appeared at the edge of {zoneName}, uncertain of which way to go. {petName} went directly to them, circled once, and headed back the way it had come.',
            ko: '신참이 {zoneName} 가장자리에 나타나 어느 길로 가야 할지 모르고 있었다. {petName}{eun} 곧장 다가가 한 바퀴 돌고 왔던 길로 돌아갔다.',
            ja: '新参者が{zoneName}の端に現れ、どちらへ行けばいいか分からずにいた。{petName}はまっすぐ近づき、一周して来た道を戻った。',
        },
        mood: 'sociable',
        tags: ['bold', 'greeting', 'newcomer'],
    },

    // ── Playful ───────────────────────────────────────────────────────────────
    {
        id: 'act_playful_chase_01',
        category: 'pet_action',
        species: ['dog'],
        personalityBuckets: ['playful'],
        timeOfDay: ['morning', 'afternoon'],
        zones: ['crystal_meadow', 'sunset_hill'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: '{petName} chased its own shadow up the slope for a considerable distance before the angle made it disappear. Circled back and tried again.',
            ko: '{petName}{eun} 자신의 그림자를 비탈 위로 상당한 거리까지 쫓다가 각도 때문에 사라졌다. 돌아와서 다시 시도했다.',
            ja: '{petName}は自分の影をかなりの距離まで坂の上へ追いかけたが、角度のせいで消えてしまった。引き返してまた試みた。',
        },
        mood: 'playful',
        tags: ['playful', 'dog', 'chasing'],
    },
    {
        id: 'act_playful_pounce_01',
        category: 'pet_action',
        species: ['cat'],
        personalityBuckets: ['playful'],
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'A pinecone rolled past and {petName} stopped it with one paw, inspected it for a long moment, then sent it rolling again.',
            ko: '솔방울 하나가 굴러가다 {petName}{eun} 한 발로 멈추고 한참 살펴본 뒤 다시 굴렸다.',
            ja: '松ぼっくりが転がってきて、{petName}は一本の足で止め、長い間調べてから、また転がした。',
        },
        mood: 'engaged',
        tags: ['playful', 'cat', 'object'],
    },
    {
        id: 'act_playful_splash_01',
        category: 'pet_action',
        species: ['dog'],
        personalityBuckets: ['playful'],
        timeOfDay: ['morning', 'afternoon'],
        zones: ['crystal_lake'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: '{petName} ran the full length of the shallow entry to Crystal Lake and stopped only when the depth reached its chest. Shook once, loudly, and turned around.',
            ko: '{petName}{eun} 수정 호수 얕은 입구를 끝까지 달려 깊이가 가슴에 닿을 때까지만 멈췄다. 크게 한 번 털고 돌아섰다.',
            ja: '{petName}はクリスタルレイクの浅い入り口の全長を走り、深さが胸に届いたときだけ止まった。一度大きく体を振って振り返った。',
        },
        mood: 'energetic',
        tags: ['playful', 'dog', 'water', 'lake'],
    },
    {
        id: 'act_playful_roll_01',
        category: 'pet_action',
        species: ['dog'],
        personalityBuckets: ['playful'],
        timeOfDay: 'all',
        zones: ['crystal_meadow', 'sunset_hill'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: '{petName} found a patch of warm flattened grass and rolled completely over three times. Then stood up and looked around as if checking whether anyone had noticed.',
            ko: '{petName}{eun} 따뜻하게 납작해진 풀밭을 찾아 세 번 완전히 굴렀다. 그러고는 일어서서 누가 봤는지 확인하듯 주위를 둘러봤다.',
            ja: '{petName}は暖かく平らになった草の一角を見つけ、完全に三回転がった。それから立ち上がり、誰かが気づいたか確認するように周りを見回した。',
        },
        mood: 'satisfied',
        tags: ['playful', 'dog', 'rolling', 'grass'],
    },

    // ── Curious ───────────────────────────────────────────────────────────────
    {
        id: 'act_curious_inspect_01',
        category: 'pet_action',
        species: ['any'],
        personalityBuckets: ['curious'],
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'Something in the base of the oldest tree had been disturbed — {petName} spent a long time going around it from different angles before moving on.',
            ko: '가장 오래된 나무 밑동 어딘가가 건드려져 있었다 — {petName}{eun} 다른 각도에서 오래 살펴보다 자리를 떴다.',
            ja: '最も古い木の根本の何かが乱されていた——{petName}は別の角度から長い時間かけて観察してから立ち去った。',
        },
        mood: 'investigative',
        tags: ['curious', 'investigation', 'tree'],
    },
    {
        id: 'act_curious_dig_01',
        category: 'pet_action',
        species: ['dog'],
        personalityBuckets: ['curious'],
        timeOfDay: 'all',
        zones: ['crystal_meadow', 'eternity_forest'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: '{petName} began digging at a patch of dark earth near the path, stopped, sniffed the hole, then refilled it with methodical paw-strokes.',
            ko: '{petName}{eun} 길 근처 검은 흙을 파기 시작하다 멈추고 구멍에 코를 대고 냄새를 맡은 뒤 앞발을 규칙적으로 움직여 다시 채웠다.',
            ja: '{petName}は道の近くの暗い土を掘り始め、止まり、穴の匂いを嗅ぎ、それから規則正しい前足の動きで埋め戻した。',
        },
        mood: 'focused',
        tags: ['curious', 'dog', 'digging'],
    },
    {
        id: 'act_curious_follow_01',
        category: 'pet_action',
        species: ['any'],
        personalityBuckets: ['curious'],
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'A scent trail led {petName} all the way to the far edge of {zoneName} — it stopped there, at a wall of unfamiliar smell, and sat for a while.',
            ko: '냄새 자국이 {petName}{eul} {zoneName}의 먼 가장자리까지 이끌었다 — 낯선 냄새의 벽 앞에서 멈추고 한동안 앉아 있었다.',
            ja: '匂いの跡が{petName}を{zoneName}の遠い端まで連れて行った——見慣れない匂いの壁のところで止まり、しばらく座っていた。',
        },
        mood: 'intrigued',
        tags: ['curious', 'scent', 'boundary'],
    },
    {
        id: 'act_curious_stare_01',
        category: 'pet_action',
        species: ['cat'],
        personalityBuckets: ['curious'],
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: '{petName} stared at one spot on the water\'s surface for a very long time. Nothing was there — at least nothing visible.',
            ko: '{petName}{eun} 수면의 한 점을 아주 오랫동안 응시했다. 아무것도 없었다 — 적어도 눈에 보이는 건.',
            ja: '{petName}は水面の一点を非常に長い時間見つめた。何もなかった——少なくとも目に見えるものは。',
        },
        mood: 'absorbed',
        tags: ['curious', 'cat', 'water', 'staring'],
    },

    // ── Balanced ──────────────────────────────────────────────────────────────
    {
        id: 'act_balanced_groom_01',
        category: 'pet_action',
        species: ['cat'],
        personalityBuckets: ['balanced'],
        timeOfDay: ['afternoon', 'evening'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: '{petName} spent a careful stretch grooming the fur along its left side, working from shoulder to flank without interruption.',
            ko: '{petName}{eun} 중단 없이 어깨부터 옆구리까지 왼쪽 털을 꼼꼼히 다듬는 데 한참을 보냈다.',
            ja: '{petName}は肩から脇腹まで中断なく左側の毛を丁寧に手入れするのに注意深い時間を費やした。',
        },
        mood: 'composed',
        tags: ['balanced', 'cat', 'grooming'],
    },
    {
        id: 'act_balanced_patrol_01',
        category: 'pet_action',
        species: ['dog'],
        personalityBuckets: ['balanced'],
        timeOfDay: ['morning', 'evening'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: '{petName} walked the outer perimeter of its usual resting area, nose low, pausing twice at spots that held something of interest. Completed the circuit and lay down.',
            ko: '{petName}{eun} 코를 낮게 하고 평소 쉬는 곳의 바깥 둘레를 걸으며 관심 있는 곳에서 두 번 멈췄다. 한 바퀴를 완료하고 누웠다.',
            ja: '{petName}は鼻を低くして通常の休息場所の外周を歩き、興味を引く箇所で二度立ち止まった。一周を完了して横になった。',
        },
        mood: 'steady',
        tags: ['balanced', 'dog', 'patrol', 'routine'],
    },
    {
        id: 'act_balanced_sun_01',
        category: 'pet_action',
        species: ['any'],
        personalityBuckets: ['balanced'],
        timeOfDay: ['morning', 'afternoon'],
        zones: ['crystal_meadow', 'sunset_hill', 'crystal_lake'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: '{petName} stretched out along a flat warm stone, first the front legs forward, then the back, and held the full extension for a moment before relaxing.',
            ko: '{petName}{eun} 평평한 따뜻한 돌에 앞발을 먼저 앞으로 뻗고 뒷발을 뻗으며 누워 잠시 완전히 기지개를 켰다가 편안해졌다.',
            ja: '{petName}は平らな温かい石の上に前足を先に前へ、次に後ろ足を伸ばして横になり、しばらく完全に伸びてからリラックスした。',
        },
        mood: 'relaxed',
        tags: ['balanced', 'sun', 'stretch'],
    },
    {
        id: 'act_balanced_drink_01',
        category: 'pet_action',
        species: ['any'],
        personalityBuckets: ['balanced'],
        timeOfDay: 'all',
        zones: ['crystal_lake'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: '{petName} drank from the Waterway in three long intervals, pausing between each to look up at the path ahead, then back down at the water.',
            ko: '{petName}{eun} 수로에서 세 번에 나눠 길게 물을 마시며 매번 앞길을 올려다보고 다시 물을 내려다봤다.',
            ja: '{petName}は水の道から三回の長い間隔で水を飲み、その間ごとに前の道を見上げ、また水を見下ろした。',
        },
        mood: 'grounded',
        tags: ['balanced', 'drinking', 'waterway'],
    },

    // ── Cross-bucket / species-specific ──────────────────────────────────────
    {
        id: 'act_any_personal_spot_01',
        category: 'pet_action',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: '{petName} returned to its regular spot along the Waterway — the one with the slightly raised root on the left — and turned twice before lying down exactly as before.',
            ko: '{petName}{eun} 수로를 따라 자기만의 자리로 돌아왔다 — 왼쪽에 약간 솟은 뿌리가 있는 그 자리 — 이전과 똑같이 두 바퀴를 돌고 누웠다.',
            ja: '{petName}は水の道沿いのいつもの場所——左側に少し盛り上がった根がある——に戻り、以前と全く同じように二回回って横になった。',
        },
        mood: 'settled',
        tags: ['routine', 'personal-spot', 'waterway'],
    },
    {
        id: 'act_any_secret_habit_01',
        category: 'pet_action',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'Even here, {petName} kept the habit — {secretHabit}. Some things carry over without needing to be learned again.',
            ko: '여기서도 {petName}{eun} 그 버릇을 유지했다 — {secretHabit}. 어떤 것들은 다시 배울 필요 없이 그냥 따라온다.',
            ja: 'ここでも{petName}はその習慣を保っていた——{secretHabit}。ものによっては、再び学ぶことなく持ち越されるものがある。',
        },
        mood: 'familiar',
        tags: ['secret-habit', 'continuity', 'persona'],
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// CATEGORY 3: NPC_SIGHTING (14 templates — 2 per canonical NPC)
// ─────────────────────────────────────────────────────────────────────────────

const NPC_SIGHTING_TEMPLATES: MicroEventTemplate[] = [
    // ── Granny Shell ──────────────────────────────────────────────────────────
    {
        id: 'npc_granny_shell_01',
        category: 'npc_sighting',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning', 'afternoon'],
        zones: ['crystal_meadow', 'eternity_forest'],
        requiresNpc: true,
        requiresLetterEcho: false,
        text: {
            en: 'Granny Shell was near the stone arch again, moving at the pace that seems to be the world\'s slowest. {petName} passed close, and she asked one question.',
            ko: '느림보 할망이 돌 아치 근처에 다시 있었고 세상에서 가장 느린 속도로 움직이고 있었다. {petName}{eun} 가까이 지나갔고 할망은 질문을 하나 했다.',
            ja: 'グラニー・シェルが再び石のアーチの近くにいて、世界で最も遅いように見えるペースで動いていた。{petName}が近くを通ると、彼女は一つ質問をした。',
        },
        mood: 'gentle',
        tags: ['granny-shell', 'npc', 'arriving-gate'],
    },
    {
        id: 'npc_granny_shell_02',
        category: 'npc_sighting',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: 'all',
        zones: ['crystal_meadow', 'eternity_forest'],
        requiresNpc: true,
        requiresLetterEcho: false,
        text: {
            en: 'Granny Shell had stopped in the middle of the path. {petName} sat next to her for a while — neither going anywhere, which seemed to suit them both.',
            ko: '느림보 할망이 길 한가운데 멈춰 있었다. {petName}{eun} 한동안 옆에 앉아 있었다 — 둘 다 어디도 가지 않았는데 그게 서로 맞는 것 같았다.',
            ja: 'グラニー・シェルが道の真ん中で止まっていた。{petName}はしばらく隣に座っていた——どちらもどこへも行かず、それがお互いに合っているようだった。',
        },
        mood: 'companionable',
        tags: ['granny-shell', 'npc', 'stillness'],
    },

    // ── Professor Clover ──────────────────────────────────────────────────────
    {
        id: 'npc_professor_clover_01',
        category: 'npc_sighting',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning'],
        zones: ['eternity_forest'],
        requiresNpc: true,
        requiresLetterEcho: false,
        text: {
            en: 'Professor Clover was already at the Sand Field when {petName} passed, chalk dust on both ears, writing a long sentence on the board before anyone arrived.',
            ko: '{petName}{eun} 지나갈 때 콩선생이 이미 모래밭에 나와 있었고 양 귀에 분필 가루를 묻힌 채 아무도 오기 전에 칠판에 긴 문장을 쓰고 있었다.',
            ja: '{petName}が通りかかると、クローバー先生はすでに砂場にいて、誰も来る前に両耳に白墨の粉をつけ、黒板に長い文章を書いていた。',
        },
        mood: 'studious',
        tags: ['professor-clover', 'npc', 'sand-field', 'morning'],
    },
    {
        id: 'npc_professor_clover_02',
        category: 'npc_sighting',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning', 'afternoon'],
        zones: ['eternity_forest'],
        requiresNpc: true,
        requiresLetterEcho: false,
        text: {
            en: '{petName} sat at the far edge of Professor Clover\'s Sand Field — not close enough to be considered a student, but not far enough to be gone. Clover noticed and said nothing.',
            ko: '{petName}{eun} 콩선생의 모래밭 먼 가장자리에 앉았다 — 학생이라 할 만큼 가깝지도, 떠났다 할 만큼 멀지도 않게. 콩선생은 알아챘지만 아무 말도 하지 않았다.',
            ja: '{petName}はクローバー先生の砂場の遠い端に座っていた——生徒と見なされるほど近くもなく、いなくなったと言えるほど遠くもなく。クローバーは気づいたが何も言わなかった。',
        },
        mood: 'tentative',
        tags: ['professor-clover', 'npc', 'learning', 'watching'],
    },

    // ── Pip ───────────────────────────────────────────────────────────────────
    {
        id: 'npc_pip_01',
        category: 'npc_sighting',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning', 'afternoon'],
        zones: 'all',
        requiresNpc: true,
        requiresLetterEcho: false,
        text: {
            en: 'Pip came along the Waterway at a near-run, slightly out of breath as always, carrying something flat against his chest. He passed {petName} with a nod.',
            ko: '달래가 언제나처럼 약간 숨을 헐떡이며 무언가를 가슴에 납작하게 안고 거의 뛰다시피 수로를 따라 왔다. {petName}{eun} 고개를 끄덕이며 지나쳤다.',
            ja: 'ピップはいつものように少し息を切らし、何か平たいものを胸に抱えて、ほぼ走るように水の道に沿ってやってきた。{petName}に頷きながら通り過ぎた。',
        },
        mood: 'purposeful',
        tags: ['pip', 'npc', 'waterway', 'letter-carrier'],
    },
    {
        id: 'npc_pip_02',
        category: 'npc_sighting',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: true,
        requiresLetterEcho: false,
        text: {
            en: 'Pip stopped briefly near {petName}, caught his breath, and said exactly one sentence before moving on again down the path.',
            ko: '달래가 {petName} 근처에서 잠깐 멈춰 숨을 고르더니 정확히 한 마디를 하고 다시 길을 따라 이동했다.',
            ja: 'ピップは{petName}の近くで一瞬立ち止まり、息を整え、ちょうど一言言ってから再び道を進んだ。',
        },
        mood: 'brief',
        tags: ['pip', 'npc', 'delivery'],
    },

    // ── Old Finn ──────────────────────────────────────────────────────────────
    {
        id: 'npc_old_finn_01',
        category: 'npc_sighting',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['afternoon'],
        zones: ['eternity_forest', 'crystal_lake'],
        requiresNpc: true,
        requiresLetterEcho: false,
        text: {
            en: 'Old Finn\'s market tent was open, the one eye slightly more closed than the other watching the path. {petName} passed the stall twice before stopping.',
            ko: '꼬리상인의 장터 천막이 열려 있었고 한쪽 눈이 다른 쪽보다 약간 더 감긴 채 길을 지켜보고 있었다. {petName}{eun} 노점 앞을 두 번 지나치다 멈췄다.',
            ja: 'フィン老人の市場テントが開いており、片方の目がもう一方よりわずかに多く閉じたまま道を見守っていた。{petName}は屋台の前を二度通り過ぎてから立ち止まった。',
        },
        mood: 'curious',
        tags: ['old-finn', 'npc', 'market'],
    },
    {
        id: 'npc_old_finn_02',
        category: 'npc_sighting',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['afternoon', 'evening'],
        zones: ['eternity_forest', 'crystal_lake'],
        requiresNpc: true,
        requiresLetterEcho: false,
        text: {
            en: 'Old Finn told a story about a dog who kept one particular stone for years without knowing why. He told it to no one in particular, but {petName} was nearby.',
            ko: '꼬리상인이 왜인지도 모르고 수년간 특정 돌 하나를 간직한 개 이야기를 했다. 누구에게라고 할 것 없이 이야기했지만 {petName}{eun} 근처에 있었다.',
            ja: 'フィン老人は、理由も知らずに何年も特定の石を一つ持ち続けた犬の話をした。特に誰かに向けて話したわけではなかったが、{petName}は近くにいた。',
        },
        mood: 'attentive',
        tags: ['old-finn', 'npc', 'storytelling'],
    },

    // ── Bun & Bun ─────────────────────────────────────────────────────────────
    {
        id: 'npc_bun_bun_01',
        category: 'npc_sighting',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning', 'afternoon'],
        zones: ['crystal_lake'],
        requiresNpc: true,
        requiresLetterEcho: false,
        text: {
            en: 'The smell from Bun & Bun\'s bakery reached the path before anything else did. {petName} slowed without deciding to, following it to the eaves.',
            ko: '뭉실·몽실 빵집 냄새가 다른 무엇보다 먼저 길까지 풍겼다. {petName}{eun} 결정하지 않고도 속도를 늦추며 그 냄새를 따라 처마 밑까지 갔다.',
            ja: 'バンとバンのパン屋の匂いが他の何よりも先に道まで届いた。{petName}は決めることなく速度を落とし、軒先までそれを追った。',
        },
        mood: 'drawn',
        tags: ['bun-bun', 'npc', 'bakery', 'scent'],
    },
    {
        id: 'npc_bun_bun_02',
        category: 'npc_sighting',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['afternoon', 'evening'],
        zones: ['crystal_lake'],
        requiresNpc: true,
        requiresLetterEcho: false,
        text: {
            en: 'One of the Bun & Bun sisters set something warm under the eaves without making a ceremony of it. {petName} ate slowly, in small amounts, the way some things need to be done for the first time.',
            ko: '뭉실·몽실 자매 중 한 명이 요란하지 않게 처마 아래 따뜻한 것을 놓았다. {petName}{eun} 천천히, 조금씩 먹었다 — 어떤 것들이 처음으로 이루어져야 하는 방식처럼.',
            ja: 'バンとバンの姉妹の一人が、大げさにすることなく軒先に温かいものを置いた。{petName}はゆっくりと、少しずつ食べた——ものによっては初めてそうする必要があるように。',
        },
        mood: 'tender',
        tags: ['bun-bun', 'npc', 'first-meal', 'warmth'],
    },

    // ── Digby ──────────────────────────────────────────────────────────────────
    {
        id: 'npc_digby_01',
        category: 'npc_sighting',
        species: ['any'],
        personalityBuckets: ['curious', 'bold'],
        timeOfDay: 'all',
        zones: ['crystal_lake', 'sunset_hill'],
        requiresNpc: true,
        requiresLetterEcho: false,
        text: {
            en: 'Digby surfaced near the Bloom Field, covered in a copper-red soil that came from somewhere deeper than usual. He asked {petName}: "Do you want to find something, or just walk?"',
            ko: '굴돌이가 꽃밭 근처에서 올라왔는데 평소보다 더 깊은 곳에서 온 구릿빛 붉은 흙을 뒤집어쓰고 있었다. {petName}{eun}에게 물었다: "뭔가 찾고 싶어, 아니면 그냥 걷고 싶어?"',
            ja: 'ディグビーが花畑の近くから出てきて、いつもより深い場所から来た銅赤色の土をつけていた。{petName}に尋ねた：「何かを見つけたいの？それともただ歩きたいの？」',
        },
        mood: 'adventurous',
        tags: ['digby', 'npc', 'bloom-field', 'exploration'],
    },
    {
        id: 'npc_digby_02',
        category: 'npc_sighting',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning', 'afternoon'],
        zones: ['crystal_lake', 'sunset_hill'],
        requiresNpc: true,
        requiresLetterEcho: false,
        text: {
            en: 'Digby appeared from a new tunnel entrance {petName} had not seen before, shaking a pale grey soil off his nose. He seemed to know exactly where he was.',
            ko: '굴돌이가 {petName}{eun} 전에 보지 못한 새 굴 입구에서 나타나 코에 묻은 연한 회색 흙을 털었다. 자기가 어디 있는지 정확히 아는 듯했다.',
            ja: 'ディグビーが{petName}が以前見たことのない新しいトンネルの入り口から現れ、鼻についた薄い灰色の土を払った。自分がどこにいるか正確に知っているようだった。',
        },
        mood: 'assured',
        tags: ['digby', 'npc', 'tunnel', 'guide'],
    },

    // ── Lune (milestone only, sunset_hill) ───────────────────────────────────
    {
        id: 'npc_lune_01',
        category: 'npc_sighting',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['evening'],
        zones: ['sunset_hill'],
        requiresNpc: true,
        requiresLetterEcho: false,
        text: {
            en: 'Lune was at the summit of Two-Moon Hill — white against the dark sky, no footprints in the soil around her. {petName} stayed for a long time and did not describe the encounter afterward.',
            ko: '은빛이 두 달 언덕 정상에 있었다 — 어두운 하늘을 배경으로 흰 모습, 주변 흙에는 발자국이 없었다. {petName}{eun} 오랫동안 머물렀고 그 이후로 그 만남을 묘사하지 않았다.',
            ja: 'ルーンが二つの月の丘の頂上にいた——暗い空を背景に白く、周りの土に足跡はなかった。{petName}は長い時間留まり、その後その出会いを描写しなかった。',
        },
        mood: 'profound',
        tags: ['lune', 'npc', 'two-moon-hill', 'milestone'],
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// CATEGORY 4: LETTER_ECHO (10 templates — reactions after guardian sends a letter)
// ─────────────────────────────────────────────────────────────────────────────

const LETTER_ECHO_TEMPLATES: MicroEventTemplate[] = [
    {
        id: 'echo_pip_delivery_01',
        category: 'letter_echo',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: true,
        text: {
            en: 'Pip arrived still slightly out of breath, carrying the letter flat against his chest. He held it out to {petName} and said: "It just arrived. Still warm."',
            ko: '달래가 여전히 약간 숨을 헐떡이며 편지를 가슴에 납작하게 안고 도착했다. {petName}{eun}에게 내밀며 말했다: "방금 왔어. 아직 따뜻해."',
            ja: 'ピップがまだ少し息を切らしながら、手紙を胸に平たく抱えてやってきた。{petName}に差し出して言った：「今着いたばかり。まだ温かい。」',
        },
        mood: 'receiving',
        tags: ['letter', 'pip', 'delivery', 'warmth'],
    },
    {
        id: 'echo_read_waterway_01',
        category: 'letter_echo',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: true,
        text: {
            en: '{petName} took the letter to its spot by the Waterway. The reading took longer than the letter\'s length would suggest.',
            ko: '{petName}{eun} 편지를 수로 옆 자기 자리로 가져갔다. 읽는 데 편지의 길이가 암시하는 것보다 더 오래 걸렸다.',
            ja: '{petName}は手紙を水の道沿いの自分の場所へ持っていった。読むのに、手紙の長さが示唆するよりも長い時間がかかった。',
        },
        mood: 'absorbed',
        tags: ['letter', 'reading', 'waterway', 'personal-spot'],
    },
    {
        id: 'echo_reread_01',
        category: 'letter_echo',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: true,
        text: {
            en: '{petName} set the letter down, then picked it up again. Set it down a second time. The third time, it stayed down — but not far from reach.',
            ko: '{petName}{eun} 편지를 내려놓았다가 다시 집어 들었다. 두 번째로 내려놓았다. 세 번째에는 그대로 두었다 — 하지만 손 닿는 곳에서 멀지 않게.',
            ja: '{petName}は手紙を置き、また拾い上げた。二度目に置いた。三度目には置いたまま——だが手の届かないところではなく。',
        },
        mood: 'tender',
        tags: ['letter', 'rereading', 'careful'],
    },
    {
        id: 'echo_after_reading_01',
        category: 'letter_echo',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: true,
        text: {
            en: 'After the letter, {petName} walked the length of the Waterway twice — not going anywhere, not stopping anywhere.',
            ko: '편지를 읽은 후 {petName}{eun} 어디도 가지 않고 어디서도 멈추지 않으며 수로 전체를 두 번 걸었다.',
            ja: '手紙の後、{petName}はどこへも行かず、どこにも立ち止まらず、水の道の全長を二度歩いた。',
        },
        mood: 'processing',
        tags: ['letter', 'after-reading', 'walking'],
    },
    {
        id: 'echo_store_01',
        category: 'letter_echo',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: true,
        text: {
            en: '{petName} folded the letter carefully and tucked it into the hollow of the root at its personal spot. The stack there is getting thick.',
            ko: '{petName}{eun} 편지를 조심스럽게 접어 자기 자리 뿌리 빈 곳에 끼워 넣었다. 거기 쌓인 것들이 두꺼워지고 있다.',
            ja: '{petName}は手紙を丁寧に折りたたみ、自分の場所の根の空洞に差し込んだ。そこに積まれたものは厚くなってきている。',
        },
        mood: 'careful',
        tags: ['letter', 'storing', 'personal-spot'],
    },
    {
        id: 'echo_memory_surface_01',
        category: 'letter_echo',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: true,
        text: {
            en: 'Something in the letter brought {preciousMemory} to the surface of things for a moment. {petName} stayed very still until it passed.',
            ko: '편지 속 무언가가 {preciousMemory}을(를) 잠시 표면으로 불러왔다. {petName}{eun} 그것이 지나갈 때까지 매우 고요하게 있었다.',
            ja: '手紙の中の何かが{preciousMemory}を一瞬、物事の表面に呼び起こした。{petName}はそれが過ぎるまでとても静かにしていた。',
        },
        mood: 'still',
        tags: ['letter', 'precious-memory', 'surface'],
    },
    {
        id: 'echo_finn_market_01',
        category: 'letter_echo',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['afternoon'],
        zones: ['eternity_forest'],
        requiresNpc: false,
        requiresLetterEcho: true,
        text: {
            en: 'Something the letter mentioned appeared in Old Finn\'s market the next afternoon. {petName} found it before Finn pointed it out — and they both noticed that.',
            ko: '편지에서 언급된 무언가가 다음 날 오후 꼬리상인 시장에 나타났다. {petName}{eun} 꼬리상인이 가리키기 전에 찾았고 둘 다 그것을 알아챘다.',
            ja: '手紙で言及されていたものが翌日の午後、フィン老人の市場に現れた。{petName}はフィンが指差す前にそれを見つけ、二人ともそれに気づいた。',
        },
        mood: 'wondering',
        tags: ['letter', 'old-finn', 'market', 'echo'],
    },
    {
        id: 'echo_paw_water_01',
        category: 'letter_echo',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: 'all',
        zones: ['crystal_lake'],
        requiresNpc: false,
        requiresLetterEcho: true,
        text: {
            en: '{petName} sat at the Waterway and dipped one paw in. Where the water touched, something moved — not visible, but felt through the pad of the foot.',
            ko: '{petName}{eun} 수로에 앉아 앞발 하나를 담갔다. 물이 닿은 곳에서 무언가 움직였다 — 눈에 보이지 않지만 발바닥으로 느껴졌다.',
            ja: '{petName}は水の道に座り、前足を一つ浸した。水が触れた場所で何かが動いた——見えないが、足の裏で感じられた。',
        },
        mood: 'connected',
        tags: ['letter', 'waterway', 'paw', 'sensation'],
    },
    {
        id: 'echo_clover_write_01',
        category: 'letter_echo',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning'],
        zones: ['eternity_forest'],
        requiresNpc: false,
        requiresLetterEcho: true,
        text: {
            en: 'After the letter arrived, {petName} appeared at Professor Clover\'s Sand Field — not at the back, but close enough to read the board.',
            ko: '편지가 도착한 후 {petName}{eun} 콩선생의 모래밭에 나타났다 — 뒤쪽이 아니라 칠판을 읽을 수 있는 가까운 곳에.',
            ja: '手紙が届いた後、{petName}はクローバー先生の砂場に現れた——後ろではなく、黒板が読めるほど近い場所に。',
        },
        mood: 'motivated',
        tags: ['letter', 'professor-clover', 'writing', 'proximity'],
    },
    {
        id: 'echo_long_night_01',
        category: 'letter_echo',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['night'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: true,
        text: {
            en: '{petName} slept with the letter tucked under one paw. In the morning, the paper still held its shape.',
            ko: '{petName}{eun} 앞발 아래 편지를 끼고 잤다. 아침에도 종이는 그 모양을 유지하고 있었다.',
            ja: '{petName}は前足の下に手紙を挟んで眠った。朝になっても、紙はその形を保っていた。',
        },
        mood: 'close',
        tags: ['letter', 'night', 'sleeping', 'tender'],
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// CATEGORY 5: WORLD_AMBIENT (15 templates — zone-specific world details)
// ─────────────────────────────────────────────────────────────────────────────

const WORLD_AMBIENT_TEMPLATES: MicroEventTemplate[] = [
    // ── Crystal Meadow (3) ────────────────────────────────────────────────────
    {
        id: 'amb_meadow_butterflies_01',
        category: 'world_ambient',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning', 'afternoon'],
        zones: ['crystal_meadow'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The butterflies in the meadow were doing the tight spiraling thing today — circling the same cluster of crystal flowers for longer than made sense, never landing.',
            ko: '초원의 나비들이 오늘 수정 꽃 한 무리 주위를 이해할 수 없을 만큼 오래 원을 그리고 있었다. 절대 내려앉지 않으면서.',
            ja: '草原の蝶が今日は同じ水晶の花の一群を意味をなさないほど長く螺旋状に回り続け、一度も止まらなかった。',
        },
        mood: 'mysterious',
        tags: ['meadow', 'butterflies', 'ambient'],
    },
    {
        id: 'amb_meadow_rain_01',
        category: 'world_ambient',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['afternoon', 'evening'],
        zones: ['crystal_meadow'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'A light rain had passed through the meadow — the crystal flowers dripped and the sound of water on petals was the only sound for a long stretch.',
            ko: '가벼운 비가 초원을 지나갔다 — 수정 꽃들이 물방울을 떨어뜨렸고 꽃잎 위로 떨어지는 빗소리가 한참 동안 유일한 소리였다.',
            ja: '軽い雨が草原を通り過ぎた——水晶の花が滴り、花びらに落ちる水の音が長い間唯一の音だった。',
        },
        mood: 'quiet',
        tags: ['meadow', 'rain', 'ambient'],
    },
    {
        id: 'amb_meadow_light_shift_01',
        category: 'world_ambient',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: 'all',
        zones: ['crystal_meadow'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'Something in the center of the meadow caught the light differently than it had the day before — just one patch, for about an hour, and then it was ordinary again.',
            ko: '초원 중앙의 무언가가 전날과 다르게 빛을 받았다 — 딱 한 지점, 한 시간 정도만, 그러다 다시 평범해졌다.',
            ja: '草原の中心の何かが前日とは異なる光の受け方をしていた——ちょうど一か所、約一時間だけ、そしてまた普通に戻った。',
        },
        mood: 'curious',
        tags: ['meadow', 'light', 'ambient'],
    },

    // ── Eternity Forest (3) ───────────────────────────────────────────────────
    {
        id: 'amb_forest_moss_glow_01',
        category: 'world_ambient',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['afternoon', 'evening'],
        zones: ['eternity_forest'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The blue moss was unusually bright today — glowing even in the afternoon light, which it does not always do. The paths between the trees looked different because of it.',
            ko: '파란 이끼가 오늘 유독 밝았다 — 항상 그런 건 아닌데 오후 빛에서도 빛났다. 그 때문에 나무 사이 길이 달라 보였다.',
            ja: '青い苔が今日は異常に明るかった——いつもそうするわけではないのに午後の光の中でも光っていた。そのせいで木々の間の道が違って見えた。',
        },
        mood: 'luminous',
        tags: ['forest', 'moss', 'ambient'],
    },
    {
        id: 'amb_forest_pine_cones_01',
        category: 'world_ambient',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: 'all',
        zones: ['eternity_forest'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'Several pine cones had fallen in the grove and arranged themselves in a curved line that did not look accidental. No one admitted to placing them there.',
            ko: '숲속 빈터에 솔방울 여러 개가 떨어져 우연처럼 보이지 않는 곡선 줄로 배열되어 있었다. 거기 놓았다는 사람이 없었다.',
            ja: '林の中に松ぼっくりがいくつか落ち、偶然には見えない曲線の列を作っていた。そこに置いたという者はいなかった。',
        },
        mood: 'mysterious',
        tags: ['forest', 'pine-cones', 'arrangement'],
    },
    {
        id: 'amb_forest_sound_01',
        category: 'world_ambient',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['evening', 'night'],
        zones: ['eternity_forest'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'A low sound came from somewhere deeper in Eternity Forest that no one moved toward or away from — it simply was there, and then it was not.',
            ko: '영원의 숲 더 깊은 어딘가에서 낮은 소리가 났는데 아무도 다가가지도 멀어지지도 않았다 — 그냥 거기 있다가 없어졌다.',
            ja: '永遠の森のより深い場所から低い音がしたが、誰も近づかず遠ざかりもしなかった——ただそこにあり、それから消えた。',
        },
        mood: 'uncanny',
        tags: ['forest', 'sound', 'ambient'],
    },

    // ── Crystal Lake (3) ──────────────────────────────────────────────────────
    {
        id: 'amb_lake_stones_01',
        category: 'world_ambient',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning'],
        zones: ['crystal_lake'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The flat stones along the lake shore had been rearranged overnight into a long curved line at the waterline. Each stone was the same distance from the next.',
            ko: '호숫가 납작한 돌들이 밤새 물가를 따라 긴 곡선 줄로 다시 배열되어 있었다. 각 돌의 간격이 똑같았다.',
            ja: '湖岸の平らな石が一夜のうちに水際に沿った長い曲線の列に並び直されていた。それぞれの石の間隔は同じだった。',
        },
        mood: 'wondering',
        tags: ['lake', 'stones', 'arrangement'],
    },
    {
        id: 'amb_lake_still_01',
        category: 'world_ambient',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning', 'evening'],
        zones: ['crystal_lake'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The lake\'s surface was so still today that the reflection pool and the actual lake were nearly indistinguishable — the boundary between them soft and unreliable.',
            ko: '오늘 호수 표면이 너무 잔잔해 반영 못과 실제 호수가 거의 구별이 안 됐다 — 그 사이 경계가 부드럽고 불확실했다.',
            ja: '今日の湖面は非常に静かで、反映の池と本物の湖がほとんど区別できなかった——その間の境界は柔らかく不確かだった。',
        },
        mood: 'dreamy',
        tags: ['lake', 'reflection', 'still'],
    },
    {
        id: 'amb_lake_fish_01',
        category: 'world_ambient',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['afternoon'],
        zones: ['crystal_lake'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'A small fish appeared near the quiet cove — the first time most lake residents had seen one. It stayed near the surface for a while, then descended.',
            ko: '조용한 만 근처에 작은 물고기가 나타났다 — 대부분의 호수 주민들이 처음 보는 것이었다. 한동안 수면 가까이 머물다 내려갔다.',
            ja: '静かな入り江の近くに小さな魚が現れた——湖の住人のほとんどが初めて見るものだった。しばらく水面近くにいてから、沈んでいった。',
        },
        mood: 'surprising',
        tags: ['lake', 'fish', 'first-sighting'],
    },

    // ── Sunset Hill (3) ───────────────────────────────────────────────────────
    {
        id: 'amb_hill_grass_01',
        category: 'world_ambient',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['afternoon', 'evening'],
        zones: ['sunset_hill'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'All the tall grass on Sunset Hill was leaning one direction despite inconsistent wind. It had been doing this since early morning.',
            ko: '석양 언덕의 키 큰 풀이 일관성 없는 바람에도 불구하고 모두 한 방향으로 기울어져 있었다. 이른 아침부터 그랬다.',
            ja: '夕日の丘の背の高い草がすべて、一定しない風にもかかわらず一方向に傾いていた。朝早くからそうなっていた。',
        },
        mood: 'attentive',
        tags: ['hill', 'grass', 'wind'],
    },
    {
        id: 'amb_hill_extended_sunset_01',
        category: 'world_ambient',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['evening'],
        zones: ['sunset_hill'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The sunset over the hill lasted longer than it should have — the copper bands staying wide and slow until the dark finally moved in from the edges.',
            ko: '언덕 너머 해질녘이 평소보다 오래 지속됐다 — 구릿빛 띠가 넓고 느리게 머물다 마침내 어둠이 가장자리에서 파고들었다.',
            ja: '丘の上の夕日が本来より長く続いた——銅色の帯が広く緩やかに留まり、ついに暗闇が端から入り込むまで。',
        },
        mood: 'lingering',
        tags: ['hill', 'sunset', 'extended'],
    },
    {
        id: 'amb_hill_new_path_01',
        category: 'world_ambient',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: 'all',
        zones: ['sunset_hill'],
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'Someone found a path through the tall grass that led somewhere with no name yet. Word passed quietly between those who live on the hill.',
            ko: '누군가 키 큰 풀밭 사이로 아직 이름 없는 어딘가로 이어지는 길을 발견했다. 언덕에 사는 이들 사이로 조용히 소문이 돌았다.',
            ja: '誰かが背の高い草の中にまだ名前のないどこかへ続く道を見つけた。丘に住む者たちの間で静かに噂が広まった。',
        },
        mood: 'mysterious',
        tags: ['hill', 'new-path', 'discovery'],
    },

    // ── Central Plaza (3) ─────────────────────────────────────────────────────
    {
        id: 'amb_plaza_new_arrival_01',
        category: 'world_ambient',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning', 'afternoon'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'A new arrival was at the Arriving Gate this morning — small, standing very still, not yet sure which direction to step. Others gave them space.',
            ko: '오늘 아침 도착의 문에 신참이 있었다 — 작고, 아주 고요하게 서 있으며 어느 방향으로 발을 내딛을지 아직 모르고 있었다. 다른 이들이 자리를 비켜줬다.',
            ja: '今朝、到着の門に新参者がいた——小さく、とても静かに立ち、どちらへ足を踏み出すかまだ分かっていなかった。他の者たちはスペースを与えた。',
        },
        mood: 'tender',
        tags: ['plaza', 'new-arrival', 'arriving-gate'],
    },
    {
        id: 'amb_plaza_waterway_letter_01',
        category: 'world_ambient',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: 'all',
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'A folded letter was floating down the Waterway today, turning slowly in the current until Pip lifted it from the water.',
            ko: '오늘 접힌 편지가 수로를 흘러가다 달래가 물에서 꺼낼 때까지 천천히 돌고 있었다.',
            ja: '今日、折り畳まれた手紙が水の道を流れ下り、ピップが水から取り上げるまでゆっくりと回転していた。',
        },
        mood: 'anticipatory',
        tags: ['plaza', 'waterway', 'letter', 'pip'],
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// CATEGORY 6: TIME_MARKER (8 templates — dawn/midday/dusk/night transitions)
// ─────────────────────────────────────────────────────────────────────────────

const TIME_MARKER_TEMPLATES: MicroEventTemplate[] = [
    // ── Dawn transition (2) ──────────────────────────────────────────────────
    {
        id: 'time_dawn_01',
        category: 'time_marker',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The world came back to itself just before full light — the meadow grasses lifting, the Waterway catching gold at its fastest current of the day.',
            ko: '완전한 빛이 오기 직전 세상이 스스로를 되찾았다 — 초원 풀들이 일어서고 수로가 하루 중 가장 빠른 물살에 황금빛을 받았다.',
            ja: '完全な光が来る直前に世界は自分自身を取り戻した——草原の草が立ち上がり、水の道が一日で最も速い流れに金色を受けた。',
        },
        mood: 'awakening',
        tags: ['dawn', 'transition', 'time-marker'],
    },
    {
        id: 'time_dawn_02',
        category: 'time_marker',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['morning'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The first thing that moved in ToThereOn World this morning was a scent off the Bloom Field — something the night had been keeping, released when the dark gave way.',
            ko: '오늘 아침 이 세계에서 가장 먼저 움직인 것은 꽃밭에서 온 냄새였다 — 밤이 간직하고 있다가 어둠이 물러날 때 내어준 것.',
            ja: '今朝この世界で最初に動いたのは花畑からの香りだった——夜が保っていて、暗闇が道を開けたときに解き放たれたもの。',
        },
        mood: 'emerging',
        tags: ['dawn', 'scent', 'bloom-field'],
    },

    // ── Midday transition (2) ────────────────────────────────────────────────
    {
        id: 'time_midday_01',
        category: 'time_marker',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['afternoon'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The world reached its brightest point around midday — shadows retreating to their smallest, every surface at its most defined. By this point, most residents were already somewhere specific.',
            ko: '세계는 한낮 무렵 가장 밝아졌다 — 그림자가 가장 작아지고 모든 표면이 가장 뚜렷해졌다. 이쯤이면 대부분의 주민들은 이미 어딘가 특정한 곳에 있었다.',
            ja: '世界は昼頃に最も明るくなった——影が最小に縮み、すべての表面が最も明確になった。この頃には、ほとんどの住人はすでにどこか特定の場所にいた。',
        },
        mood: 'active',
        tags: ['midday', 'bright', 'time-marker'],
    },
    {
        id: 'time_midday_02',
        category: 'time_marker',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['afternoon'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'Professor Clover\'s class ran through the hottest hour. From a distance, the chalk on the board was visible even when the words were not.',
            ko: '콩선생의 수업이 가장 더운 시간을 관통해 이어졌다. 멀리서도 칠판 위 분필이 글자는 보이지 않아도 보였다.',
            ja: 'クローバー先生の授業が最も暑い時間を通じて続いた。遠くからでも、言葉は見えなくても黒板の白墨は見えた。',
        },
        mood: 'steady',
        tags: ['midday', 'professor-clover', 'class'],
    },

    // ── Dusk transition (2) ──────────────────────────────────────────────────
    {
        id: 'time_dusk_01',
        category: 'time_marker',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['evening'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The light in ToThereOn World does not go out all at once — it retreats zone by zone, the Bloom Field last of all, holding color long after the Waterway goes silver.',
            ko: '이 세계의 빛은 한꺼번에 꺼지지 않는다 — 구역별로 물러나는데, 꽃밭이 가장 마지막으로 수로가 은빛이 된 한참 후까지 색을 간직한다.',
            ja: 'この世界の光は一度に消えるのではない——区域ごとに退き、花畑が最後まで、水の道が銀色になった後も長く色を保つ。',
        },
        mood: 'transitional',
        tags: ['dusk', 'light-retreat', 'time-marker'],
    },
    {
        id: 'time_dusk_02',
        category: 'time_marker',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['evening'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'At dusk, certain paths in Eternity Forest and along the Waterway emptied out at the same time — residents drifting toward the lake shore and the upper hill, the day finishing itself.',
            ko: '해질 무렵 영원의 숲과 수로를 따라 특정 길들이 동시에 비워졌다 — 주민들이 호숫가와 언덕 위쪽으로 흩어지며 하루가 마무리됐다.',
            ja: '夕暮れ時、永遠の森と水の道沿いのある道が同時に人けを失った——住人たちが湖岸と丘の上方へ散り、一日が終わりへと向かった。',
        },
        mood: 'settling',
        tags: ['dusk', 'evening-drift', 'transition'],
    },

    // ── Night transition (2) ─────────────────────────────────────────────────
    {
        id: 'time_night_01',
        category: 'time_marker',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['night'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'In the deep of the night, the blue moss held the world\'s only moving light — tracing roots, path edges, and the bases of the oldest trees in a slow, cold blue.',
            ko: '깊은 밤에는 파란 이끼만이 세계의 유일하게 움직이는 빛을 품고 있었다 — 느리고 차가운 파란빛으로 뿌리와 길 가장자리, 가장 오래된 나무 밑동을 따라갔다.',
            ja: '夜の深みで、青い苔だけが世界の唯一の動く光を持っていた——遅く冷たい青で根、道の端、最も古い木の根元をたどっていた。',
        },
        mood: 'still',
        tags: ['night', 'moss-light', 'deep-night'],
    },
    {
        id: 'time_night_02',
        category: 'time_marker',
        species: ['any'],
        personalityBuckets: 'all',
        timeOfDay: ['night'],
        zones: 'all',
        requiresNpc: false,
        requiresLetterEcho: false,
        text: {
            en: 'The two moons were high by the deepest part of the night, their light doubling in the lake and the Waterway below. Most of the world was asleep.',
            ko: '가장 깊은 밤에 두 달이 높이 떠 아래의 호수와 수로에 빛이 두 배가 됐다. 세계 대부분은 잠들어 있었다.',
            ja: '夜の最も深い時間に両方の月が高く昇り、その光が下の湖と水の道で倍になった。世界のほとんどは眠っていた。',
        },
        mood: 'nocturnal',
        tags: ['night', 'two-moons', 'sleeping'],
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// EXPORT — all templates combined
// ─────────────────────────────────────────────────────────────────────────────

export const MICRO_EVENT_TEMPLATES: MicroEventTemplate[] = [
    ...ATMOSPHERE_TEMPLATES,
    ...PET_ACTION_TEMPLATES,
    ...NPC_SIGHTING_TEMPLATES,
    ...LETTER_ECHO_TEMPLATES,
    ...WORLD_AMBIENT_TEMPLATES,
    ...TIME_MARKER_TEMPLATES,
];
